# Generated by Django 5.1.5 on 2025-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='current_engagement_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='desired_engagement_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
